# Generated by Django 4.1.1 on 2022-10-02 09:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('baits_count', models.FloatField(blank=True, null=True, verbose_name='Baits count')),
            ],
        ),
        migrations.CreateModel(
            name='RoniPolygons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_origin', models.IntegerField(blank=True, choices=[(0, 'Ronis files'), (1, 'Timi')], null=True)),
                ('timi_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=2039)),
                ('baits_num', models.IntegerField(blank=True, null=True)),
                ('orig_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoniRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_origin', models.IntegerField(blank=True, choices=[(0, 'Ronis files'), (1, 'Timi')], null=True)),
                ('timi_id', models.IntegerField(blank=True, null=True)),
                ('timi_related_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('baits_num', models.IntegerField(blank=True, null=True)),
                ('orig_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('origin_files', models.CharField(blank=True, max_length=500, null=True)),
                ('route', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=2039)),
            ],
        ),
        migrations.CreateModel(
            name='PixelByDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('baits_count', models.FloatField(blank=True, null=True, verbose_name='Baits count')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_calculated', models.DateField(blank=True, null=True)),
                ('orig_id', models.IntegerField(blank=True, null=True)),
                ('timi_id', models.IntegerField(blank=True, null=True)),
                ('timi_related_id', models.IntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('main_pixel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixel_by_date', to='baits_app.pixel')),
                ('polygonmodel_polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixels_by_date', to='baits_app.ronipolygons')),
                ('routesmodel_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixels_by_date', to='baits_app.roniroutes')),
            ],
        ),
    ]
